### ISSUE TITLE
Add GFS v16.3.12 fix file updates to develop

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/GSI-fix#11]
GSI PR [#636](https://github.com/NOAA-EMC/GSI/pull/636) updates three files in files in the operational global GSI `fix`:

1. `global_anavinfo.l127.txt` - add entry for new file `Rcov_crisn21`
2. `global_satinfo.txt` - down weight NOAA-21 CrIS-FSR radiances relative to NOAA-20
3. `Rcov_crisn21` - NOAA-21 CrIS-FSR correlated error file (new binary file)   

ASCII GSI fix files are version controlled in NOAA-EMC/GSI-fix.  EID maintains copies of GSI binary fix files in various locations.

This issue is opened to document the updating of ASCII GSI fix files (1 and 2 above) in NOAA-EMC/GSI-fix `develop`.   A separate global-workflow issue will be opened to add the new `Rcov_crisn21` binary GSI fix file.

**Comment by RussTreadon-NOAA** [comment]
Work for this issue is being done in [`RussTreadon-NOAA/GSI-fix:release/gfs.v16.3.10`](https://github.com/RussTreadon-NOAA/GSI-fix/tree/release/gfs.v16.3.10).

**Comment by KateFriedman-NOAA** [comment]
@RussTreadon-NOAA Checking on the status of this. Let me know if you're waiting on me for anything related to this. I can pull the GSI fix updates into the primary GFS fix set when ready, just let me know.

**Comment by RussTreadon-NOAA** [comment]
@KateFriedman-NOAA , linking in @ADCollard for a status update.

**Comment by ADCollard** [comment]
@KateFriedman-NOAA @RussTreadon-NOAA This was waiting on the CRTM 2.4.0.1 being added to the spack-stack which I see is now the case, so I can work on moving this forward (although it is now v16.3.12)

**Comment by KateFriedman-NOAA** [comment]
@ADCollard Great! @DavidHuber-NOAA just opened https://github.com/NOAA-EMC/GSI/issues/674, which includes the update to `crtm/2.4.0.1`. We can wrap this issue into the work to update to spack-stack 1.6.0.

**Comment by RussTreadon-NOAA** [comment]
Rename `release/gfs.v16.3.10` as [`release/gfs.v16.3.12`](https://github.com/RussTreadon-NOAA/GSI-fix/tree/release/gfs.v16.3.12) to match the version number at which these fix file changes were implemented.

**Comment by RussTreadon-NOAA** [comment]
Close with PR #13
