### ISSUE TITLE
New convinfo, anavinfo files for GSI soil analysis

### ISSUE THREAD

**Issue by ClaraDraper-NOAA** [NOAA-EMC/GSI-fix#12]
Global_workflow PR [2263](https://github.com/NOAA-EMC/global-workflow/pull/2263) will add initial capability to include a soil analysis in the GSI. 

The soil analysis requires changes to the convinfo file (turning on the assimilation of T2m and q2m) and the anavinfo file (addition of relevant state variables to the various namelists). 

Examples of the new files are here on hera: 
/scratch2/BMC/gsienkf/Clara.Draper/2mDAfiles_gworkflow/

For the near-future, the global workflow will select the alternative *info files only when the soil analysis flag is selected. To complete that PR we will need to add the alternative *info files to the GSIfix directory.

**Comment by ClaraDraper-NOAA** [comment]
@ADCollard If you can let me know how you'd like me to add the files (file names?) I can prepare a PR.

**Comment by ADCollard** [comment]
@ClaraDraper-NOAA I have added your changes to my fork https://github.com/ADCollard/GSI-fix.git.  Please check I have it right.  I will next merge in the remaining changes from recent operational upgrades.  And then issue a PR.

**Comment by ClaraDraper-NOAA** [comment]
@ADCollard These changes are correct. However, I wasn't expecting these to go into the main convinfo and anavinfo files until we've done some more testing - since this means we'll be turning on the land DA in the standard runs (although I'm all for more land DA!). I was thinking that my files would be added as alternatives. I need to check, but I'm not sure if the GSI will run with these changes, without a namelist change. So, if we are going to add my changes to to the main files, I'll need to make that namelist change in my PR. I'm flying home tomorrow - but can meet quickly on Monday if it would be easier to quickly discuss this.

**Comment by ADCollard** [comment]
@ClaraDraper-NOAA I am a little confused here.   I was assuming this was already tested.   I am not sure that we usually add test files to develop, but I am not the code manager.

Probably the best thing to do is for me to back out your changes and let you submit a separate PR.   I do not see a compelling reason why these need to be combined, especially if you just want to add extra files.  All @KateFriedman-NOAA wants is a single timestamp of GSI-fix once the dust has settled.

Adding @KateFriedman-NOAA @RussTreadon-NOAA @CatherineThomas-NOAA @WalterKolczynski-NOAA who might be able to advise on how best to do this.

**Comment by CatherineThomas-NOAA** [comment]
@ADCollard 
This feature is likely to be included in v17 but is not ready to be included by default.   Alternative convinfo/anavinfo files are not planned as a permanent solution, but they will help with testing and follows good version control practices of not pointing to personal spaces. 

I agree that @ClaraDraper-NOAA's changes can be in a separate GSI-fix PR and don't need to be merged as a part of your PR, so long as Clara takes into account your new changes in her files.  And this is certainly one of the downsides of the alternative file strategy, having to update multiple versions.  

@RussTreadon-NOAA @KateFriedman-NOAA Any suggestions/alternatives?

**Comment by KateFriedman-NOAA** [comment]
> @KateFriedman-NOAA Any suggestions/alternatives?

No additional suggestions or alternatives from me. I agree with @CatherineThomas-NOAA 's comment about avoiding personal copies though. I leave decision in DA hands. Appreciate being included. :)
