### ISSUE TITLE
Infrared cloud and aerosol detection software (CADS) ascii namelist files for the GSI

### ISSUE THREAD

**Issue by wx20jjung** [NOAA-EMC/GSI-fix#18]
A new infrared cloud detection routine has been added to the GSI.  Specific quality control / cloud detection files are needed for each instrument using this new routine.  At this time, the GSI is setup to use CADS for the AIRS, CrIS and IASI instruments.  These files contain the quality control / cloud detection parameters for these 3 instruments.

These 3 files reside in https://github.com/wx20jjung/GSI-fix.git in the fix-CADS branch.

**Comment by RussTreadon-NOAA** [comment]
PR #19 merged
